### ISSUE TITLE
Загруженная игра не высвечивается в «установленных играх»

### ISSUE THREAD

**Issue by w201403** [instead-hub/instead-launcher#1]
Приветствую и благодарю за отличную программу INSTEAD launcher, которая облегчает нам жизнь.

Об ошибке
---------------------

Ошибка заключается в том, что загруженная и распакованная игра «Инстедоз - 5» не высветилась в указанном перечне (снимок прилагаю):
![20170923 - 0001](https://user-images.githubusercontent.com/19310702/30771532-8349b3bc-a052-11e7-8fa5-5b17e6074a76.png)

Другие высвечиваются там совершенно нормально.
Тем не менее, в перечне игр, доступном из самого INSTEAD, «Инстедоз - 5» присутствует (снимок прилагаю) и запускается как ни в чём не бывало:
![20170923 - 0002](https://user-images.githubusercontent.com/19310702/30771531-8348ef90-a052-11e7-8f4e-56ea88c93a6c.png)

Я пытался сам найти в системе материалы INSTEAD launcher, чтобы, возможно, с налёта обнаружить там причину ошибки, но у меня не получилось :)

О системе
---------------------

System:
           Kernel: 4.10.0-35-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.4.6 (Gtk 3.18.9-1ubuntu3.3) dm: mdm Distro: Linux Mint 18.2 Sonya

Repos:
           Active apt sources in file: /etc/apt/sources.list.d/instead-instead-launcher-xenial.list
           deb http: //ppa.launchpad.net/instead/instead-launcher/ubuntu xenial main
           deb-src http: //ppa.launchpad.net/instead/instead-launcher/ubuntu xenial main
           Active apt sources in file: /etc/apt/sources.list.d/instead-ppa-xenial.list
           deb http: //ppa.launchpad.net/instead/ppa/ubuntu xenial main
           deb-src http: //ppa.launchpad.net/instead/ppa/ubuntu xenial main

**Comment by hugeping** [comment]
какая версия instead-launcher? Я думаю, в вашем дистрибутиве просто старая версия, которая не поддерживает stead3 игры.
Нужна версия 0.7.0. Если версия ниже -- это не баг.

**Comment by hugeping** [comment]
да, я посмотрел. На ланчпаде версия 0.6.xx.
У нас нет людей, которые бы поддерживали deb сборки. Так что придется собрать самому из git или не использовать ланчер.

**Comment by w201403** [comment]
Спасибо! Я подумал, что если подключить репозиторий, то будет обновляться сам )
Спасибо вам

> У нас нет людей, которые бы поддерживали deb сборки.

По этому поводу написал вам на почту. Если необходимо обратиться по-другому, пожалуйста, сообщите, как.
